EXTERNAL_DATA_PATH = "/path/to/external_data"
OUTPUT_DATA_PATH = "/path/to/output/file"
WORD2VEC_MODEL_PATH = "/path/to/model"
FASTTEXT_MODEL_PATH = "/path/to/model"
TOYGER_DATA_FILE_PATH = "/path/to/toyger/data.pkl"
