# a path to the model which was previously converted using the following
# command:
# tweet_recommendations/scripts/convert_embeddings_model_to_mmap \
#  --fast \
#  models/keyedvectors/<name_of_the_model>.bin \
#  models/keyedvectors/<the_same_name_of_the_model>.bin
model_path: "experiments/tweet2vec_our_dataset_model"
last_epoch: -1
popularity_to_similarity_ratio: 0.3
